defaults:
  - _self_
  - env: cartpole
  - alg: mpc

exp_name: mpc_benchmarks

id: ${hydra.job.id}

general:
  num_envs: 256
  play: True # sets no_grad=True
  logdir: logs/tmp/mpc/
  save_interval: False
  render: False
  device: cuda:0
  run_wandb: True
  seed: 0
  train: True

# env-specific defaults for different algs
env:
  gamma: 0.99
