_target_: shac.algorithms.ahac.AHAC
_recursive_: False
actor_config:
  _target_: shac.models.actor.ActorStochasticMLP
  units: ${resolve_child:[64,64],${env.ahac.actor_mlp},units}
  activation: elu
critic_config:
  _target_: shac.models.critic.DoubleCriticMLP
  units: ${resolve_child:[64,64],${env.ahac.critic_mlp},units}
  activation: elu
actor_lr: ${resolve_child:2e-3,${env.ahac},actor_lr}
critic_lr: ${resolve_child:2e-3,${env.ahac},critic_lr}
lr_schedule: linear
obs_rms: True
ret_rms: False
critic_iterations: # if None train until convergence
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:2000,${env.shac},max_epochs}
steps_min: 8
steps_num: 64
contact_threshold: 3000
grad_norm: 1.0
save_interval: ${resolve_child:400,${env.shac},save_interval}
stochastic_eval: False
eval_runs: 12
train: ${general.train}
device: ${general.device}
