name: warp_cartpole
config:
  _target_: shac.envs.CartPoleSwingUpWarpEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 1024
  seed: ${general.seed}
  episode_length: 240
  no_grad: ${general.play}
  stochastic_init: False
  early_termination: False
  ag_return_body: True

shac:
  actor_lr: 1e-3
  critic_lr: 1e-2
  max_epochs: 500
  betas:
    - 0.7
    - 0.95

shac2:
  critic_lr: 1e-3

ppo:
  max_epochs: 500
  minibatch_size: 1920
  save_interval: 100
  save_best_after: 50
  num_actors: 32
  steps_num: 240

player:
  games_num: 12
  num_actors: 4
