name: df_hopper
env_name: HopperEnv

config:
  _target_: shac.envs.HopperEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 1024
  seed: ${general.seed}
  episode_length: 1000
  no_grad: ??? # decided based on algorithm
  stochastic_init: True
  MM_caching_frequency: 4
  early_termination: True
  contact_ke: 2e4
  contact_kd:

shac:
  actor_lr: 2e-3
  critic_lr: 4e-3
  max_epochs: 500
  betas: [0.7, 0.95]
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 400

shac2:
  actor_lr: 2e-3
  critic_lr: 4e-3
  max_epochs: 500
  betas: [0.7, 0.95]
  actor_mlp:
    units: [128, 128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 400

ppo:
  max_epochs: 500
  minibatch_size: 8192
  num_actors: 1024
  steps_num: 240
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
